import * as THREE from './three.module.min.js';
const $=id=>document.getElementById(id);
let token=null, session=null, state=null, states=[], selected=null, busy=false, approval=null;
let toastTimer, sceneVersion='', checkedCameras=new Set();
function log(message,error=false){const row=document.createElement('div');row.className='log-entry'+(error?' error':'');const time=document.createElement('time');time.textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false});row.append(time,document.createTextNode(message));$('log').prepend(row);while($('log').children.length>60)$('log').lastChild.remove();}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6000);}
function availability(){document.querySelectorAll('[data-live]').forEach(b=>b.disabled=!state||busy);document.querySelectorAll('form button').forEach(b=>{if(!b.closest('dialog'))b.disabled=busy||(b.hasAttribute('data-live')&&!state)||(!token&&!b.closest('#create-form'));});$('approve').disabled=busy;$('reject').disabled=busy;$('quick-room').disabled=busy;$('refresh').disabled=busy||!token;$('instances').disabled=busy;document.querySelectorAll('#joints input').forEach(i=>i.disabled=busy);$('busy-label').textContent=busy?'执行中…':'就绪';}
function numbers(id,n){const a=$(id).value.trim().split(/[,，\s]+/).map(Number);if(a.length!==n||a.some(x=>!Number.isFinite(x)))throw Error(`请输入 ${n} 个有效数字：${id}`);return a;}
function integer(id,min,max){const n=Number($(id).value);if(!Number.isInteger(n)||n<min||n>max)throw Error(`数值应为 ${min}–${max} 的整数`);return n;}
async function api(path,body){const response=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Loop-Token':token},body:JSON.stringify(body)}:{cache:'no-store'});const data=await response.json();if(!response.ok){if(data.requests&&Object.keys(data.requests).length){const entries=Object.entries(data.requests);approval=entries[entries.length-1][0];$('approval-content').textContent=JSON.stringify(entries[entries.length-1][1],null,2);$('approval-dialog').showModal();const waiting=Error('等待你在页面确认本次操作');waiting.pending=true;throw waiting;}throw Error(data.error||`HTTP ${response.status}`);}return data;}
async function tool(name,args={}){if(!token){$('help-dialog').showModal();throw Error('请先打开本地工作台服务');}return (await api('/api/tool',{name,args})).result;}
function liveArgs(extra={}){if(!state)throw Error('请先创建仿真实例');return {instance:state.instance,...extra};}
async function run(label,fn){if(busy)return;busy=true;availability();try{const value=await fn();if(value?.path?.endsWith('.hdf5'))dataset(value);log(label+' · 完成');}catch(e){log(label+' · '+e.message,!e.pending);if(!e.pending)toast(e.message);}finally{if(token){try{await refresh();}catch(e){log('状态同步失败：'+e.message,true);}}busy=false;availability();}}
async function refresh(){const response=await api('/api/state');states=response.instances;const id=state?.instance||$('instances').value;state=states.find(s=>s.instance===id)||states[0]||null;renderState();}

// Shared room recipe: preview is explicitly labelled; real creation uses receipts.
const room=[
 ['floor',[0,0,-.05],[4,4,.1],'#d2d8cf'],['wall_back',[0,2,1.25],[4.12,.12,2.5],'#c0c8bb'],
 ['wall_left',[-2,0,1.25],[.12,4,2.5],'#c9d1c3'],['wall_right',[2,.7,1.25],[.12,2.6,2.5],'#c0c8bb'],
 ['desk_top',[-.75,.65,.75],[1.3,.65,.08],'#aa8867'],
 ...[[-1.3,.4],[-.2,.4],[-1.3,.9],[-.2,.9]].map(([x,y],i)=>['desk_leg_'+i,[x,y,.355],[.07,.07,.71],'#7c6957']),
 ['wardrobe',[1.45,1.55,1],[.7,.65,2],'#859580']
];
function rgba(hex){return [parseInt(hex.slice(1,3),16)/255,parseInt(hex.slice(3,5),16)/255,parseInt(hex.slice(5,7),16)/255,1];}
async function create(template=$('template').value){const backend=$('backend').value;if(template==='arm'&&backend!=='mujoco')throw Error('机械臂示例适用于 MuJoCo；Isaac 请导入 USD 机器人');const args={backend};if(template==='arm')args.scene=session.example_scene;if(template==='file'){args.scene=$('scene-path').value.trim();if(!args.scene)throw Error('请输入场景路径');}const made=await tool('sim_create',args);state=made;selected=null;checkedCameras.clear();log(`已创建 ${backend} 实例`);if(template==='room'){for(const [name,position,size,color]of room){await tool('sim_edit',liveArgs({operation:'box',config:{name,position,size,mass:0,color:rgba(color)}}));log('已添加 '+name);}}await refresh();home();}

// Z-up orbit viewer, local Three.js bundle; no remote assets or page telemetry.
const scene=new THREE.Scene();scene.background=new THREE.Color('#eff2ee');
const camera=new THREE.PerspectiveCamera(42,1,.01,200);camera.up.set(0,0,1);
const group=new THREE.Group();scene.add(group);
scene.add(new THREE.HemisphereLight(0xffffff,0x7d8c75,2.5));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(-3,-4,9);scene.add(sun);
const grid=new THREE.GridHelper(16,80,0xc1cbc0,0xdce2d7);grid.rotation.x=Math.PI/2;grid.position.z=-.065;scene.add(grid);
let renderer=null;
try{renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;$('canvas-host').append(renderer.domElement);}catch(e){log('三维渲染不可用：'+e.message,true);$('view-label').textContent='WebGL 不可用；仍可操作并采集相机画面';}
let theta=-.85,phi=.92,distance=9,target=new THREE.Vector3(0,0,.6),drag=null;
function home(){theta=-.85;phi=.92;distance=state?.bodies&&Object.keys(state.bodies).length<6?4.5:9;target.set(0,0,.6);draw();}
function draw(){if(!renderer)return;const box=$('canvas-host').getBoundingClientRect();if(!box.width||!box.height)return;renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.position.set(target.x+distance*Math.sin(phi)*Math.cos(theta),target.y+distance*Math.sin(phi)*Math.sin(theta),target.z+distance*Math.cos(phi));camera.lookAt(target);camera.updateProjectionMatrix();renderer.render(scene,camera);}
new ResizeObserver(draw).observe($('canvas-host'));
function geometry(item){const a=item.size||[];switch(item.type){case'box':return new THREE.BoxGeometry(...a.map(x=>Math.max(x,.001)));case'sphere':return new THREE.SphereGeometry(a[0],24,16);case'ellipsoid':return new THREE.SphereGeometry(1,24,16).scale(...a);case'capsule':return new THREE.CapsuleGeometry(a[0],2*a[1],8,16).rotateX(Math.PI/2);case'cylinder':return new THREE.CylinderGeometry(a[0],a[0],2*a[1],24).rotateX(Math.PI/2);case'mesh':{const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(item.vertices,3));g.setIndex(item.indices);g.computeVertexNormals();return g;}default:return null;}}
function rebuild(items){while(group.children.length){const child=group.children[0];group.remove(child);child.geometry.dispose();child.material.dispose();}for(const item of items){const geom=geometry(item);if(!geom)continue;const c=item.color||[.6,.7,.6,1];const material=new THREE.MeshStandardMaterial({color:new THREE.Color(c[0],c[1],c[2]),roughness:.8,transparent:c[3]<1,opacity:c[3]??1,side:THREE.DoubleSide});const mesh=new THREE.Mesh(geom,material);mesh.position.fromArray(item.position);if(item.rotation){const r=item.rotation;mesh.quaternion.setFromRotationMatrix(new THREE.Matrix4().set(r[0],r[1],r[2],0,r[3],r[4],r[5],0,r[6],r[7],r[8],0,0,0,0,1));}mesh.userData.name=item.name;group.add(mesh);}highlight();}
function highlight(){for(const mesh of group.children)mesh.material.emissive.set(mesh.userData.name===selected?0x164a31:0x000000);draw();}
function select(name){selected=name;$('selected-name').textContent=name||'无';if(state?.bodies[name])$('move-position').value=state.bodies[name].map(x=>Number(x.toFixed(4))).join(', ');$('selection-panel').open=!!name;document.querySelectorAll('.object-row').forEach(b=>b.classList.toggle('selected',b.dataset.name===name));highlight();}
if(renderer){const el=renderer.domElement;el.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY};el.setPointerCapture(e.pointerId);});el.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(e.shiftKey){target.x-=dx*.002*distance;target.y+=dy*.002*distance;}else{theta-=dx*.006;phi=Math.max(.12,Math.min(1.53,phi+dy*.006));}drag.x=e.clientX;drag.y=e.clientY;draw();});el.addEventListener('pointerup',e=>{if(drag&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<5){const rect=el.getBoundingClientRect(),ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObjects(group.children)[0];if(hit)select(hit.object.userData.name);}drag=null;});el.addEventListener('pointercancel',()=>drag=null);el.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(.4,Math.min(60,distance*Math.exp(e.deltaY*.001)));draw();},{passive:false});}

function renderState(){const current=state?.instance;$('instances').replaceChildren();for(const [i,s]of states.entries()){const option=new Option(`${s.backend} · 场景 ${i+1}`,s.instance);$('instances').add(option);}if(!states.length)$('instances').add(new Option('尚未创建',''));$('instances').value=current||'';$('objects').replaceChildren();const names=state?Object.keys(state.bodies):room.map(r=>r[0]);$('object-count').textContent=names.length;for(const name of names){const b=document.createElement('button');b.className='object-row';b.dataset.name=name;b.textContent=name;b.onclick=()=>select(name);$('objects').append(b);}$('empty-tip').hidden=!!state;$('time').textContent=(state?.time||0).toFixed(3);$('backend-label').textContent=state?`${state.backend} ${state.version}`:'未运行';$('scene-source').textContent=state?'仿真器状态 · 已同步':'示例布局 · 未运行仿真';$('view-label').textContent=state?(state.layout?.kind==='bounds'?'Isaac 包围盒布局 · 非完整模型':'MuJoCo 几何布局 · 实际状态'):'示例布局 · 非仿真结果';rebuild(state?.layout?.items||room.map(([name,position,size,color])=>({name,position,size,color:rgba(color),type:'box'})));if(selected&&!names.includes(selected))selected=null;select(selected);const signature=state?state.instance+JSON.stringify(state.action_space):'';if(signature!==sceneVersion){sceneVersion=signature;$('joints').replaceChildren();(state?.action_space.names||[]).forEach((name,i)=>{const row=document.createElement('div');row.className='joint';const label=document.createElement('label');label.textContent=name;const input=document.createElement('input');input.type='number';input.step='.01';input.dataset.joint=i;input.setAttribute('aria-label',name);input.value=state.action[i]||0;const bound=state.action_space.bounds[i];if(bound){input.min=bound[0];input.max=bound[1];}row.append(label,input);$('joints').append(row);});}$('action-kind').textContent=state?.action_space.names.length?state.action_space.kind+' · '+state.action_space.names.length+' 维':'当前场景没有执行器。';$('camera-list').replaceChildren();for(const [name,c]of Object.entries(state?.cameras||{})){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=name;input.checked=checkedCameras.has(name);input.onchange=()=>input.checked?checkedCameras.add(name):checkedCameras.delete(name);label.append(input,document.createTextNode(`${name} · ${c.width} × ${c.height}`));$('camera-list').append(label);}$('evaluation').textContent=state?.task?`${state.task.name} · ${state.evaluation.verdict} · reward ${state.evaluation.reward.toFixed(3)}`:'尚未设置任务。';availability();}
function action(){return [...document.querySelectorAll('#joints input')].map(i=>{const v=Number(i.value);if(!Number.isFinite(v))throw Error('控制输入必须为有效数字');return v;});}
function cameraNames(){const names=[...checkedCameras].filter(n=>state?.cameras[n]);if(!names.length)throw Error('请先创建并勾选相机');return names;}
function cameraView(on){$('viewport').hidden=on;$('camera-view').hidden=!on;$('layout-tab').classList.toggle('active',!on);$('image-tab').classList.toggle('active',on);if(!on)draw();}
function captureCards(result){$('captures').replaceChildren();$('camera-view').querySelector('.camera-empty').hidden=true;for(const [name,c]of Object.entries(result.cameras)){const card=document.createElement('article');card.className='capture-card';const title=document.createElement('h3');title.textContent=`${name} · ${result.observation.backend} 快照 · ${result.observation.time.toFixed(3)} s`;const img=document.createElement('img');img.src=c.rgb;img.alt=`${name} 相机实际渲染图`;card.append(title,img);for(const [text,url]of [['RGB PNG',c.rgb],['深度 / 分割 NPZ',c.arrays]]){const a=document.createElement('a');a.href=url;a.textContent=text;a.download='';card.append(a);}const details=document.createElement('details'),summary=document.createElement('summary'),pre=document.createElement('pre');summary.textContent='标定与实例标签';pre.textContent=JSON.stringify({intrinsics:c.intrinsics,camera_to_world:c.camera_to_world,labels:c.labels},null,2);details.append(summary,pre);card.append(details);$('captures').append(card);}cameraView(true);}
function dataset(result){const card=document.createElement('div');card.className='dataset';const a=document.createElement('a');a.href=result.path;a.download='';a.textContent='↓ 下载 episode HDF5';const small=document.createElement('small');small.textContent=`${result.transitions} transitions · 任务 ${result.evaluation.verdict} · 未训练`;card.append(a,small);$('datasets').prepend(card);}

$('help').onclick=()=>$('help-dialog').showModal();$('home-view').onclick=home;$('layout-tab').onclick=()=>cameraView(false);$('image-tab').onclick=()=>cameraView(true);$('template').onchange=()=>$('scene-path-label').hidden=$('template').value!=='file';
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(t=>t.classList.toggle('active',t===b));['build','cameras','learning'].forEach(p=>$('panel-'+p).hidden=p!==b.dataset.panel);});
$('instances').onchange=()=>{state=states.find(s=>s.instance===$('instances').value)||null;selected=null;checkedCameras.clear();$('captures').replaceChildren();renderState();};
$('quick-room').onclick=()=>run('创建房间场景',()=>create('room'));$('create-form').onsubmit=e=>{e.preventDefault();run('创建场景',()=>create());};$('refresh').onclick=()=>run('同步状态',async()=>{});
$('box-form').onsubmit=e=>{e.preventDefault();run('添加物体',()=>tool('sim_edit',liveArgs({operation:'box',config:{name:$('box-name').value.trim(),position:numbers('box-position',3),size:numbers('box-size',3),mass:Number($('box-mass').value),color:rgba($('box-color').value)}})));};
$('move-form').onsubmit=e=>{e.preventDefault();run('移动对象',()=>{if(!selected)throw Error('请先选中对象');return tool('sim_edit',liveArgs({operation:'move',config:{name:selected,position:numbers('move-position',3)}}));});};
$('remove').onclick=()=>run('删除对象',()=>{if(!selected)throw Error('请先选中对象');return tool('sim_edit',liveArgs({operation:'remove',config:{name:selected}}));});
$('import-form').onsubmit=e=>{e.preventDefault();run('导入资产',()=>tool('sim_edit',liveArgs({operation:$('asset-kind').value,config:{name:$('asset-name').value.trim(),path:$('asset-path').value.trim(),position:numbers('asset-position',3)}})));};
$('step').onclick=()=>run('物理步进',()=>tool('sim_step',liveArgs({action:action(),steps:integer('steps',1,1000)})));
$('reset').onclick=()=>run('重置实例',async()=>{const r=await tool('sim_reset',liveArgs({seed:integer('seed',0,2147483647)}));document.querySelectorAll('#joints input').forEach((el,i)=>el.value=r.action[i]||0);return r;});
$('close-instance').onclick=()=>run('关闭实例',()=>tool('sim_close',liveArgs()));
$('camera-form').onsubmit=e=>{e.preventDefault();run('创建相机',async()=>{const name=$('camera-name').value.trim();const r=await tool('sim_camera',liveArgs({config:{name,parent:$('camera-parent').value.trim(),position:numbers('camera-position',3),quaternion:numbers('camera-quaternion',4),width:integer('camera-width',16,1024),height:integer('camera-height',16,1024),fovy:Number($('camera-fovy').value)}}));checkedCameras.add(name);return r;});};
$('capture').onclick=()=>run('相机采集',async()=>captureCards(await tool('sim_capture',liveArgs({cameras:cameraNames()}))));
$('task-form').onsubmit=e=>{e.preventDefault();run('设置任务',()=>tool('sim_task',liveArgs({task:{name:$('task-name').value.trim(),seed:integer('seed',0,2147483647),horizon:integer('horizon',1,10000),success:[{kind:'position',body:$('task-body').value.trim(),target:numbers('task-target',3),tolerance:Number($('task-tolerance').value)}]}})));};
$('record').onclick=()=>run('采集数据',()=>tool('sim_record',liveArgs({actions:Array.from({length:integer('record-count',1,100)},()=>action()),cameras:cameraNames(),steps:integer('steps',1,1000)})));
$('approve').onclick=()=>{const id=approval;$('approval-dialog').close();run('审批并执行',async()=>{const r=(await api('/api/approve',{id,allow:true})).result;if(r.cameras&&r.observation)captureCards(r);return r;});};
$('reject').onclick=()=>{const id=approval;$('approval-dialog').close();run('拒绝操作',()=>api('/api/approve',{id,allow:false}));};
renderState();draw();
try{session=await api('/api/session');if(!session.token)throw Error('Static site');token=session.token;$('connection').textContent='本地服务已连接';$('connection').classList.add('connected');log('本地服务已连接 · '+session.permissions.mode+' 模式');await refresh();}catch(e){token=null;$('connection').textContent='静态预览';log('启动 loop web 后可执行仿真；当前为示例布局。');}availability();
